export const mockUsers = [
  // {
  //   name: "Paco Gomez",
  //   email: "gomex@g.es",
  //   password: 12345,
  //   genero: "Hombre",
  //   edad: '34',
  //   localidad: 'trebujena',
  //   foto: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80',
  //   fumador: false,
  //   deportista: true,
  //   cinefilo: true,
  //   playa: true,
  // },
  // {
  //   name: "Juan Pardo",
  //   email: "par@g.es",
  //   password: 12345,
  //   genero: "Hombre",
  //   edad: '34',
  //   localidad: 'trebujena',
  //   foto: 'https://images.unsplash.com/photo-1543984613-f55ca6a1ba35?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
  //   fumador: false,
  //   deportista: true,
  //   cinefilo: true,
  //   playa: true,
  // },
  // {
  //   name: "Enrique Gomez",
  //   email: "gomez@g.es",
  //   password: 12345,
  //   genero: "Hombre",
  //   edad: '34',
  //   localidad: 'trebujena',
  //   foto: 'https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80',
  //   fumador: false,
  //   deportista: true,
  //   cinefilo: true,
  //   playa: true,
  // },
  // {
  //   name: "Manuela",
  //   email: "manu@g.es",
  //   password: 12345,
  //   genero: "Mujer",
  //   edad: '34',
  //   localidad: 'trebujena',
  //   fumador: false,
  //   deportista: true,
  //   foto: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80',
  //   cinefilo: true,
  //   playa: true,
  // },
  // {
  //   name: "Enriqueta",
  //   email: "Enriqueta@g.es",
  //   password: 12345,
  //   genero: "Mujer",
  //   edad: '34',
  //   localidad: 'trebujena',
  //   fumador: false,
  //   deportista: true,
  //   foto: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80',
  //   cinefilo: true,
  //   playa: true,
  // },
  // {
  //   name: "Habichuela",
  //   email: "Habichuela@g.es",
  //   password: 12345,
  //   genero: "Mujer",
  //   edad: '34',
  //   localidad: 'Barcelona',
  //   fumador: false,
  //   deportista: true,
  //   foto: 'https://images.unsplash.com/photo-1491349174775-aaafddd81942?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80',
  //   cinefilo: true,
  //   playa: true,
  // },
  // {
  //   name: "Canarito_reshulon",
  //   email: "Canarito_reshulon@g.es",
  //   password: 12345,
  //   genero: "Hombre",
  //   edad: '34',
  //   localidad: 'trebujena',
  //   fumador: false,
  //   foto: 'https://images.unsplash.com/photo-1568602471122-7832951cc4c5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
  //   deportista: true,
  //   cinefilo: true,
  //   playa: true,
  // },
  // {
  //   name: "sa-rubia",
  //   email: "sa-rubia@g.es",
  //   password: 12345,
  //   genero: "Mujer",
  //   edad: '34',
  //   localidad: 'trebujena',
  //   fumador: false,
  //   foto: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=688&q=80',
  //   deportista: true,
  //   cinefilo: true,
  //   playa: true,
  // },
  // {
  //   name: "Ana",
  //   email: "gomex@g.es",
  //   password: 12345,
  //   genero: "Mujer",
  //   edad: '34',
  //   localidad: 'trebujena',
  //   fumador: false,
  //   foto: 'https://images.unsplash.com/photo-1520466809213-7b9a56adcd45?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80',
  //   deportista: true,
  //   cinefilo: true,
  //   playa: true,
  // },
  {
    name: "Angie Jolie",
    email: "jolie@g.es",
    password: 12345,
    genero: "Mujer",
    edad: '46',
    foto: 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/angelina-jolie-vestido-negro-1570091726.jpg?crop=1.00xw:0.503xh;0,0&resize=640:*',
    localidad: 'trebujena',
    fumador: false,
    deportista: true,
    cinefilo: true,
    playa: true,
  },
  // {
  //   name: "Scarlett",
  //   email: "scarlett@g.es",
  //   password: 12345,
  //   genero: "Mujer",
  //   edad: '34',
  //   foto: 'https://cdn-3.expansion.mx/83/93/527b88be4f259d44ada9ef0560cd/scarlett-johansson1.jpg',
  //   localidad: 'mojados',
  //   fumador: false,
  //   deportista: true,
  //   cinefilo: true,
  //   playa: true,
  // },
  // {
  //   name: "Melissa",
  //   email: "benoist@g.es",
  //   password: 12345,
  //   genero: "Mujer",
  //   edad: '34',
  //   foto: 'https://es.web.img3.acsta.net/pictures/19/12/18/20/43/5013155.jpg',
  //   localidad: 'madrid',
  //   fumador: false,
  //   deportista: true,
  //   cinefilo: true,
  //   playa: true,
  // },
  // {
  //   name: "Leo",
  //   email: "leo@g.es",
  //   password: 12345,
  //   genero: "Hombre",
  //   edad: '34',
  //   foto: 'https://i.pinimg.com/originals/65/4a/52/654a52a1a70d0ea787ce40ff57f56254.jpg',
  //   localidad: 'barcelona',
  //   fumador: false,
  //   deportista: true,
  //   cinefilo: true,
  //   playa: true,
  // },
  // {
  //   name: "Tom",
  //   email: "tom@g.es",
  //   password: 12345,
  //   genero: "Hombre",
  //   edad: '34',
  //   foto: 'https://bolavip.com/export/sites/bolavip/img/2021/04/27/gettyimages-1158547102.jpg_799894230.jpg',
  //   localidad: 'paris',
  //   fumador: false,
  //   deportista: true,
  //   cinefilo: true,
  //   playa: true,
  // },
  // {
  //   name: "Benedict",
  //   email: "ben@g.es",
  //   password: 12345,
  //   genero: "Hombre",
  //   edad: '34',
  //   foto: 'https://images.moviefit.me/p/o/3267-benedict-cumberbatch.jpg',
  //   localidad: 'roma',
  //   fumador: false,
  //   deportista: true,
  //   cinefilo: true,
  //   playa: true,
  // },
  // {
  //   name: "Timothée",
  //   email: "ben@g.es",
  //   password: 12345,
  //   genero: "Hombre",
  //   edad: '34',
  //   foto: 'https://e00-telva.uecdn.es/assets/multimedia/imagenes/2021/09/16/16317870417608.jpg',
  //   localidad: 'berlin',
  //   fumador: false,
  //   deportista: true,
  //   cinefilo: true,
  //   playa: true,
  // },
  // {
  //   name: "Marie",
  //   email: "marie@g.es",
  //   password: 12345,
  //   genero: "Mujer",
  //   edad: '34',
  //   foto: 'https://inlovemag.com/wp-content/uploads/2020/06/Maria-A-thegem-blog-timeline-large.jpg',
  //   localidad: 'earth',
  //   fumador: false,
  //   deportista: true,
  //   cinefilo: true,
  //   playa: true,
  // },
];