export const mockUsers = [
  // {
  //   name: "Paco Gomez",
  //   email: "gomex@g.es",
  //   password: "12345",
  //   genero: "Hombre",
  //   edad: '34',
  //   localidad: 'trebujena',
  //   foto: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80',
  //   fumador: false,
  //   deportista: true,
  //   cinefilo: true,
  //   playa: true,
  // },
  // {
  //   name: "Juan Pardo",
  //   email: "par@g.es",
  //   password: "12345",
  //   genero: "Hombre",
  //   edad: '34',
  //   localidad: 'trebujena',
  //   foto: 'https://images.unsplash.com/photo-1543984613-f55ca6a1ba35?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
  //   fumador: false,
  //   deportista: true,
  //   cinefilo: true,
  //   playa: true,
  // },
  // {
  //   name: "Enrique Gomez",
  //   email: "gomez@g.es",
  //   password: "12345",
  //   genero: "Hombre",
  //   edad: '34',
  //   localidad: 'trebujena',
  //   foto: 'https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80',
  //   fumador: false,
  //   deportista: true,
  //   cinefilo: true,
  //   playa: true,
  // },
  // {
  //   name: "Manuela",
  //   email: "manu@g.es",
  //   password: "12345",
  //   genero: "Mujer",
  //   edad: '34',
  //   localidad: 'trebujena',
  //   fumador: false,
  //   deportista: true,
  //   foto: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80',
  //   cinefilo: true,
  //   playa: true,
  // },
  // {
  //   name: "Enriqueta",
  //   email: "Enriqueta@g.es",
  //   password: "12345",
  //   genero: "Mujer",
  //   edad: '34',
  //   localidad: 'trebujena',
  //   fumador: false,
  //   deportista: true,
  //   foto: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80',
  //   cinefilo: true,
  //   playa: true,
  // },
  // {
  //   name: "Habichuela",
  //   email: "Habichuela@g.es",
  //   password: "12345",
  //   genero: "Mujer",
  //   edad: '34',
  //   localidad: 'Barcelona',
  //   fumador: false,
  //   deportista: true,
  //   foto: 'https://images.unsplash.com/photo-1491349174775-aaafddd81942?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80',
  //   cinefilo: true,
  //   playa: true,
  // },
  // {
  //   name: "Canarito_reshulon",
  //   email: "Canarito_reshulon@g.es",
  //   password: "12345",
  //   genero: "Hombre",
  //   edad: '34',
  //   localidad: 'trebujena',
  //   fumador: false,
  //   foto: 'https://images.unsplash.com/photo-1568602471122-7832951cc4c5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
  //   deportista: true,
  //   cinefilo: true,
  //   playa: true,
  // },
  // {
  //   name: "sa-rubia",
  //   email: "sa-rubia@g.es",
  //   password: "12345",
  //   genero: "Mujer",
  //   edad: '34',
  //   localidad: 'trebujena',
  //   fumador: false,
  //   foto: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=688&q=80',
  //   deportista: true,
  //   cinefilo: true,
  //   playa: true,
  // },
  // {
  //   name: "Ana",
  //   email: "gomex@g.es",
  //   password: "12345",
  //   genero: "Mujer",
  //   edad: '34',
  //   localidad: 'trebujena',
  //   fumador: false,
  //   foto: 'https://images.unsplash.com/photo-1520466809213-7b9a56adcd45?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80',
  //   deportista: true,
  //   cinefilo: true,
  //   playa: true,
  // },

  // USUARIOS OFICIALES

  {
    name: "Kate Winslet",
    email: "kate@gmail.com",
    password: "12345",
    genero: "Mujer",
    edad: '46',
    foto: 'https://media.vogue.es/photos/5efc3e66f25f467f55fe9348/2:3/w_2560%2Cc_limit/GettyImages-488206480.jpg',
    localidad: 'Reading',
    fumador: true,
    deportista: true,
    cinefilo: true,
    playa: false,
    montaña: true,
  },
  {
    name: "Nicole",
    email: "nicole@gmail.com",
    password: "12345",
    genero: "Mujer",
    edad: '54',
    foto: 'https://static.wikia.nocookie.net/doblaje/images/8/8f/Nicole-kidman-2018.jpg/revision/latest?cb=20181030173738&path-prefix=es',
    localidad: 'Honolulu',
    fumador: false,
    deportista: true,
    cinefilo: true,
    playa: false,
    montaña: true,
  },
  {
    name: "Brad Pitt",
    email: "brad@gmail.com",
    password: "12345",
    genero: "Hombre",
    edad: '57',
    foto: 'https://media.fashionnetwork.com/cdn-cgi/image/fit=contain,width=1000,height=1000/m/0d2f/313d/73c9/143a/6875/d46e/d976/bb81/2b1d/b017/b017.jpg',
    localidad: 'Shawnee',
    fumador: false,
    deportista: true,
    cinefilo: true,
    playa: false,
    montaña: false,
  },
  {
    name: "Zendaya",
    email: "zen@gmail.com",
    password: "12345",
    genero: "Mujer",
    edad: '25',
    foto: 'https://i.pinimg.com/564x/9e/66/76/9e66765948e562b65d2f6bde2c4d6bd8.jpg',
    localidad: 'Oakland',
    fumador: false,
    deportista: true,
    cinefilo: true,
    playa: true,
    montaña: true,
  },
  {
    name: "Jordi",
    email: "jordi@gmail.com",
    password: "12345",
    genero: "Hombre",
    edad: '27',
    foto: 'https://m.media-amazon.com/images/M/MV5BYTU5ZWJhZDctNGZlOS00NjRjLWFiNGMtNDU0NmIwNTM1Y2ViXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_UY1200_CR85,0,630,1200_AL_.jpg',
    localidad: 'Puertollano',
    fumador: true,
    deportista: true,
    cinefilo: true,
    playa: true,
    montaña: true,
  },
  {
    name: "Belén",
    email: "belen@gmail.com",
    password: "12345",
    genero: "Mujer",
    edad: '48',
    foto: 'https://hips.hearstapps.com/dm.h-cdn.co/assets/16/22/980x1273/1465148051-new-article.jpg?resize=480:*',
    localidad: 'Madrid',
    fumador: true,
    deportista: false,
    cinefilo: false,
    playa: true,
    montaña: false,
  },
  {
    name: "Pepa",
    email: "pepa@gmail.com",
    password: "12345",
    genero: "Mujer",
    edad: '45',
    foto: 'https://i.redd.it/to1un6h9slt51.jpg',
    localidad: 'Brístol',
    fumador: true,
    deportista: false,
    cinefilo: true,
    playa: false,
    montaña: false,
  },
  {
    name: "Elsa",
    email: "pepa@gmail.com",
    password: "12345",
    genero: "Mujer",
    edad: '27',
    foto: 'http://images6.fanpop.com/image/photos/38300000/Elsa-in-real-life-childhood-animated-movie-heroines-38329207-600-800.jpg',
    localidad: 'Arendelle',
    fumador: false,
    deportista: false,
    cinefilo: true,
    playa: true,
    montaña: true,
  },
  {
    name: "Hércules",
    email: "her@gmail.com",
    password: "12345",
    genero: "Hombre",
    edad: '30',
    foto: 'https://shangay.com/sites/default/files/hercules.jpg',
    localidad: 'Atenas',
    fumador: false,
    deportista: true,
    cinefilo: true,
    playa: true,
    montaña: false,
  },
  {
    name: "Aladdín",
    email: "al@gmail.com",
    password: "12345",
    genero: "Hombre",
    edad: '26',
    foto: 'https://purosarcasmo.net/wp-content/uploads/2018/10/Pr%C3%ADncipes-Disney-4.jpg',
    localidad: 'Ágrabah',
    fumador: false,
    deportista: true,
    cinefilo: false,
    playa: true,
    montaña: true,
  },

  {
    name: "Tarzán",
    email: "tar@gmail.com",
    password: "12345",
    genero: "Hombre",
    edad: '24',
    foto: 'https://www.okchicas.com/wp-content/uploads/2015/07/Principes-de-disney-reales-8.jpg',
    localidad: 'La Selva',
    fumador: false,
    deportista: true,
    cinefilo: false,
    playa: true,
    montaña: true,
  },
  {
    name: "Angie Jolie",
    email: "jolie@gmail.com",
    password: "12345",
    genero: "Mujer",
    edad: '46',
    foto: 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/angelina-jolie-vestido-negro-1570091726.jpg?crop=1.00xw:0.503xh;0,0&resize=640:*',
    localidad: 'Los Ángeles',
    fumador: false,
    deportista: true,
    cinefilo: true,
    playa: true,
    montaña: true,
  },
  {
    name: "Scarlett",
    email: "scarlett@gmail.com",
    password: "12345",
    genero: "Mujer",
    edad: '37',
    foto: 'https://cdn-3.expansion.mx/83/93/527b88be4f259d44ada9ef0560cd/scarlett-johansson1.jpg',
    localidad: 'Manhattan',
    fumador: false,
    deportista: true,
    cinefilo: true,
    playa: true,
    montaña: false,
  },
  {
    name: "Melissa",
    email: "mel@gmail.com",
    password: "12345",
    genero: "Mujer",
    edad: '33',
    foto: 'https://es.web.img3.acsta.net/pictures/19/12/18/20/43/5013155.jpg',
    localidad: 'Houston',
    fumador: false,
    deportista: true,
    cinefilo: true,
    playa: true,
    montaña: true,
  },
  {
    name: "Leo",
    email: "leo@gmail.com",
    password: "12345",
    genero: "Hombre",
    edad: '24',
    foto: 'https://i.pinimg.com/originals/65/4a/52/654a52a1a70d0ea787ce40ff57f56254.jpg',
    localidad: 'Los Ángeles',
    fumador: false,
    deportista: true,
    cinefilo: true,
    playa: true,
    montaña: true,
  },
  {
    name: "Tom",
    email: "tom@gmail.com",
    password: "12345",
    genero: "Hombre",
    edad: '25',
    foto: 'https://bolavip.com/export/sites/bolavip/img/2021/04/27/gettyimages-1158547102.jpg_799894230.jpg',
    localidad: 'Kingston',
    fumador: false,
    deportista: true,
    cinefilo: true,
    playa: true,
    montaña: false,
  },
  {
    name: "Benedict",
    email: "ben@gmail.com",
    password: "12345",
    genero: "Hombre",
    edad: '45',
    foto: 'https://images.moviefit.me/p/o/3267-benedict-cumberbatch.jpg',
    localidad: 'Londres',
    fumador: false,
    deportista: true,
    cinefilo: true,
    playa: true,
    montaña: true,
  },
  {
    name: "Timothée",
    email: "tim@gmail.com",
    password: "12345",
    genero: "Hombre",
    edad: '25',
    foto: 'https://e00-telva.uecdn.es/assets/multimedia/imagenes/2021/09/16/16317870417608.jpg',
    localidad: 'Manhattan',
    fumador: true,
    deportista: true,
    cinefilo: true,
    playa: false,
    montaña: false,
  },
  {
    name: "Marie",
    email: "marie@gmail.com",
    password: "12345",
    genero: "Mujer",
    edad: '34',
    foto: 'https://inlovemag.com/wp-content/uploads/2020/06/Maria-A-thegem-blog-timeline-large.jpg',
    localidad: 'Thunder Bay',
    fumador: false,
    deportista: true,
    cinefilo: true,
    playa: false,
    montaña: true,
  },
  {
    name: "Isabel I",
    email: "isa@gmail.com",
    password: "12345",
    genero: "Mujer",
    edad: '46',
    foto: 'https://media.vogue.es/photos/5efc3e66f25f467f55fe9348/2:3/w_2560%2Cc_limit/GettyImages-488206480.jpg',
    localidad: 'Madrigal',
    fumador: false,
    deportista: true,
    cinefilo: true,
    playa: false,
    montaña: true,
  },
];