export const mockUsers = [
  {
    name: "Paco Gomez",
    email: "gomex@g.es",
    password: 12345,
    genero: "Hombre",
    edad: '34',
    localidad: 'trebujena',
    fumador: false,
    deportista: true,
    cinefilo: true,
    playa: true,

  },
  {
    name: "Juan Pardo",
    email: "par@g.es",
    password: 12345,
    genero: "Hombre",
    edad: '34',
    localidad: 'trebujena',
    fumador: false,
    deportista: true,
    cinefilo: true,
    playa: true,
  },
  {
    name: "Enrique Gomez",
    email: "gomez@g.es",
    password: 12345,
    genero: "Hombre",
    edad: '34',
    localidad: 'trebujena',
    fumador: false,
    deportista: true,
    cinefilo: true,
    playa: true,
  },
  {
    name: "Manuela",
    email: "manu@g.es",
    password: 12345,
    genero: "Mujer",
    edad: '34',
    localidad: 'trebujena',
    fumador: false,
    deportista: true,
    cinefilo: true,
    playa: true,
  },
  {
    name: "Enriqueta",
    email: "Enriqueta@g.es",
    password: 12345,
    genero: "Mujer",
    edad: '34',
    localidad: 'trebujena',
    fumador: false,
    deportista: true,
    cinefilo: true,
    playa: true,
  },
  {
    name: "Habichuela",
    email: "Habichuela@g.es",
    password: 12345,
    genero: "Mujer",
    edad: '34',
    localidad: 'Barcelona',
    fumador: false,
    deportista: true,
    cinefilo: true,
    playa: true,
  },
  {
    name: "Canarito_reshulon",
    email: "Canarito_reshulon@g.es",
    password: 12345,
    genero: "Hombre",
    edad: '34',
    localidad: 'trebujena',
    fumador: false,
    deportista: true,
    cinefilo: true,
    playa: true,
  },
  {
    name: "sa-rubia",
    email: "sa-rubia@g.es",
    password: 12345,
    genero: "Mujer",
    edad: '34',
    localidad: 'trebujena',
    fumador: false,
    deportista: true,
    cinefilo: true,
    playa: true,
  },
  {
    name: "Ana",
    email: "gomex@g.es",
    password: 12345,
    genero: "Mujer",
    edad: '34',
    localidad: 'trebujena',
    fumador: false,
    deportista: true,
    cinefilo: true,
    playa: true,
  },
  {
    name: "Angie Jolie",
    email: "jolie@g.es",
    password: 12345,
    genero: "Mujer",
    edad: '34',
    foto: 'https://almomento.mx/wp-content/uploads/2021/08/Angelina-Jolie-debuta-en-Instagram.jpg',
    localidad: 'trebujena',
    fumador: false,
    deportista: true,
    cinefilo: true,
    playa: true,
  },
];